
server: 
  port: 8081
  servlet.context-path: /api # 访问地址：http://localhost:8081/api/hi
  tomcat.uri-encoding: UTF-8  
   
spring:  
  datasource:  
    url: jdbc:mysql://localhost:3306/bubuxiu?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=true
    username: root  
    password: root  
    driverClassName: com.mysql.jdbc.Driver
    filters : stat,log4j2
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 10
    initialSize: 2
    maxWait: 60000
    maxIdle: 5
    minIdle: 2
    defaultAutoCommit: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20
    # druid 监控日志输出间隔
    timeBetweenLogStatsMillis: 60000
#    statLogger: myStatLogger
  jackson: #jackson
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
          # 超时
          shutdown-timeout: 100
      #连接超时时间
      timeout: 10000
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    type-aliases-package: com.buxiu.bootexample.po #,com.buxiu.bootexample.vo
    mapper-locations: classpath:com/buxiu/bootexample/mapper/*Mapper.xml
     
 
# logging
logging: 
    config: classpath:log4j2/log4j2-spring.xml





